config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  resources :venues, only: [:index, :show, :new, :create, :destroy]

  root 'venues#index'
  get 'venues/:id' => 'venue#show'
  get 'venues/new' => 'venue#new'
  post 'venues' => 'venue#create'
  delete 'venues/:id' => 'venue#destroy'
 

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/venue.rb
class Venue < ApplicationRecord
    has_many :views, dependent: :destroy_async 
  end
  

app/models/view.rb
class View < ApplicationRecord
    belongs_to :venue
  end
  

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/venues_controller.rb
class VenuesController < ApplicationController

  def index
    @venues = Venue.all
    @views = View.all
  end

  def show
    @venue = Venue.find(params[:id])
    @views = @venue.views
    
  end

  def new
    @venue = Venue.new
  end

  def create
    @venue = Venue.new(venue_params)
    
    if @venue.save
      redirect_to @venue, notice: "Venue has been created"
    else
      render :new 
    end
  end
  

  def destroy 
    @venue = Venue.find(params[:id])
    @venue.destroy
    redirect_to root_path, notice: "Venue has been deleted"
  end 

  private

  def venue_params
    params.require(:venue).permit(:name, :location)
  end
  




end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/venues_helper.rb
module VenuesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>


  <nav class="navbar">
  <div class="container">
    <a class="navbar-brand" href="/">SeatView</a>
    <ul class="navbar-nav"> 
      <li><%= link_to 'Login', new_user_session_path %></li>
    </ul>
  </div>
</nav>

  
  <%= yield %>
  
<head>
  <title>SeatView</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
<%= stylesheet_link_tag "navbar", media: 'all', 'data-turbolinks-track' => true %>


  <%= javascript_importmap_tags %>
</head>



<body>
  
</body>

</html>

app/views/venues/button.html.erb
<%= stylesheet_link_tag('button') %>

app/views/venues/index.html.erb
<h1>Venues</h1>
<ul>
  <% @venues.each do |venue| %>
    <li>
      <%= link_to "#{venue.name}, #{venue.location}", venue_path(venue) %>
    </li>
     
  <% end %>
</ul>
<%= link_to "Create a new Venue", new_venue_path %>

app/views/venues/navbar.html.erb
<%= stylesheet_link_tag('navbar') %>

app/views/venues/new.html.erb
<h2>Create a New Venue</h2>

<div id="new-venue">
  
    <%= form_with model: @venue, url: venues_path, local: true, method: :post do |form| %>
      <div class="field">
        <%= form.label :name %>
        <%= form.text_field :name %>
      </div>
      <div class="field">
        <%= form.label :location %>
        <%= form.text_field :location %>
      </div>
      <!-- Add other fields as needed -->
      <div class="actions">
        <%= form.submit 'Create Venue' %>
      </div>
    <% end %>
 
</div>

app/views/venues/show.html.erb
<h3><%= @venue.name %></h3>
<p><%= @venue.location %></p>

<h4>Views:</h4>
<ul>
  <% @venue.views.each do |view| %>
    <li>
      Section: <%= view.section %>, Row: <%= view.row %>, Seat: <%= view.seat %>
      <!-- You can also display the view image if available -->
      <% if view.view.present? %>
        <img src="<%= view.view %>" alt="View Image" width="500">
      <% end %>
    </li>
  <% end %>
</ul>


<%= button_to "Delete Venue", (@venue), method: :delete, data: { confirm: "Are you sure you want to delete this post?" }, class: "delete-button" %>

app/views/welcome/index.html.erb
<h1>Welcome to SeatView App</h1>